default_platform(:android)
platform :android do
 desc "Generate build and upload to firebase"
 lane :build do

   gradle(
     task: "assemble",
     build_type: ENV['BUILD_TYPE'],
     properties: {
       "android.injected.signing.store.file" => ENV['KEYSTORE_FILE'],
       "android.injected.signing.store.password" => ENV['KEYSTORE_PASS'],
       "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
       "android.injected.signing.key.password" => ENV['KEY_PASS'],
     }
   )

   firebase_app_distribution(
     app: ENV["FIREBASE_APP_ID"],
     release_notes_file: "releaseNotes.txt",
     groups: "Internal",
     firebase_cli_token: ENV['FIREBASE_CI_TOKEN'],
     debug: false
   )
    end
end